name: ‚¨• Deploy
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: 18.17.0

jobs:
  deploy:
    name: üöÄ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ‚Üß Checkout code
        uses: actions/checkout@v3

      - name: ‚¨£ Install dependencies
        run: npm ci

      - name: üõ†Ô∏è Build site
        run: npm run build

      - name: üöÄ Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ./dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          PUBLIC_TURNSTILE_SITEKEY: ${{ vars.PUBLIC_TURNSTILE_SITEKEY }}
